version: 0.2

phases: 
  install: 
    commands:
      - echo Installing Node
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - apt install -y nodejs
  pre_build:
    commands:
      - echo Installing Dependencies
      - npm install
  build:
    commands:
      - echo Testing
      - npm test
      - echo Building
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
